import jsPDF from 'jspdf'

interface PdfParams {
  reading: string
  clientName?: string
  signOrDob: string
  scopeList: string[]
  style: string
  date: string
}

export function generateReadingPdf(params: PdfParams) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 25

  function checkPageBreak(needed: number) {
    if (y + needed > 278) {
      doc.addPage()
      y = 20
    }
  }

  // Header
  doc.setFontSize(18)
  doc.setTextColor(100, 60, 180)
  doc.text('ASTRARA', margin, y)
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 150)
  doc.text('Reading Studio', margin + 48, y)
  y += 10

  doc.setDrawColor(220, 220, 220)
  doc.line(margin, y, pageWidth - margin, y)
  y += 10

  // Title
  doc.setFontSize(14)
  doc.setTextColor(40, 40, 40)
  const title = params.clientName ? `Reading for ${params.clientName}` : 'Your Cosmic Reading'
  doc.text(title, margin, y)
  y += 7

  doc.setFontSize(9)
  doc.setTextColor(140, 140, 140)
  doc.text(`${params.signOrDob}  ·  ${params.style}  ·  ${params.date}`, margin, y)
  y += 5
  doc.text(`Scope: ${params.scopeList.join(', ')}`, margin, y)
  y += 8

  doc.line(margin, y, pageWidth - margin, y)
  y += 10

  // Strip markdown formatting
  const stripped = params.reading
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/^[-*]\s+/gm, '  · ')

  // Split into ## sections
  const rawSections = stripped.split(/^## /m).filter(Boolean)

  for (const section of rawSections) {
    const lines = section.split('\n')
    const header = lines[0].replace(/\s*—.*$/, '').trim()
    const body = lines.slice(1).join('\n').trim()

    // Section header
    checkPageBreak(20)
    y += 3
    doc.setFontSize(12)
    doc.setTextColor(100, 60, 180)
    const headerWrapped = doc.splitTextToSize(header, maxWidth)
    for (const hl of headerWrapped) {
      doc.text(hl, margin, y)
      y += 6
    }
    y += 2

    // Section body — split by ### sub-headers
    const subSections = body.split(/^### /m)

    for (let si = 0; si < subSections.length; si++) {
      const sub = subSections[si]
      if (!sub.trim()) continue

      const subLines = sub.split('\n')

      // Render sub-header (for si > 0 — the first split part is before any ###)
      if (si > 0) {
        checkPageBreak(15)
        y += 2
        doc.setFontSize(11)
        doc.setTextColor(80, 60, 140)
        doc.text(subLines[0].trim(), margin, y)
        y += 6
        subLines.shift()
      }

      // Render body text
      doc.setFontSize(10)
      doc.setTextColor(60, 60, 60)
      const text = subLines.join('\n').trim()
      if (!text) continue

      const paragraphs = text.split(/\n\n+/)
      for (const para of paragraphs) {
        const trimPara = para.trim()
        if (!trimPara) continue
        const rendered = doc.splitTextToSize(trimPara.replace(/\n/g, ' '), maxWidth)
        for (const line of rendered) {
          checkPageBreak(6)
          doc.text(line, margin, y)
          y += 5.5
        }
        y += 3
      }
    }
  }

  // Footer on last page
  const pages = doc.getNumberOfPages()
  doc.setPage(pages)
  doc.setFontSize(8)
  doc.setTextColor(180, 180, 180)
  doc.text('Generated by Astrara  ·  astrara.app  ·  Part of Harmonic Waves', margin, 290)

  const safeName = (params.clientName || 'cosmic').toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
  doc.save(`astrara-reading-${safeName}-${params.date}.pdf`)
}
