import type { ZodiacSign } from '../../types'

export interface SunInSignReading {
  general: string
  themeKeywords: string[]
  personalByHouse: Record<number, string>
}

export const SUN_IN_SIGN: Record<ZodiacSign, SunInSignReading> = {
  aries: {
    general: 'The Sun in Aries marks the beginning of the astrological year — a burst of cardinal fire that calls everyone to act boldly. Vitality is high, patience is low, and the collective energy favours pioneering spirit over careful planning. This is a season to start things, to lead, and to rediscover what makes you feel alive.',
    themeKeywords: ['initiative', 'courage', 'new beginnings', 'vitality'],
    personalByHouse: {
      1: 'The Aries Sun energises your sense of self with pioneering spirit. You feel ready to reinvent yourself, take initiative, and express your identity with bold clarity. This is your season to lead.',
      2: 'Your earning potential and sense of personal value receive a burst of cardinal fire. Take courageous action around finances — ask for the raise, launch the venture, or assert your worth with confidence.',
      3: 'Your voice carries assertive, pioneering energy. Speaking up, writing boldly, or initiating important conversations comes naturally. Siblings and neighbours may play a more prominent role in your life now.',
      4: 'Dynamic energy stirs your domestic sphere. You may feel driven to make dramatic changes to your living situation, address family tensions directly, or bring fresh vitality into your private world.',
      5: 'Creative courage surges through you. This is an extraordinary time for starting artistic projects, pursuing romance with boldness, or rediscovering the joy of play and spontaneous self-expression.',
      6: 'Your daily routines benefit from more vigour and decisiveness. Start the fitness programme, overhaul your diet, or take charge of a health concern you have been neglecting. Your body responds well to action now.',
      7: 'Partnerships require honest assertion of your needs. The balance between independence and togetherness is highlighted — speak your truth to partners while remaining open to their perspective.',
      8: 'Deep change accelerates with courage and directness. Face the difficult truths, confront what needs to end, and trust that letting go of the old creates space for powerful renewal.',
      9: 'Your hunger for adventure and new horizons is ignited. Travel, higher education, philosophical exploration, or simply broadening your worldview through new experiences feeds your soul deeply.',
      10: 'Professional ambition and initiative are powerfully activated. This is a time to start new projects, assert your leadership, and take bold risks in your career. Fortune favours the brave now.',
      11: 'Your social vision becomes more assertive and action-oriented. Lead group projects, champion causes that matter, or energise your community with your enthusiasm and willingness to go first.',
      12: 'The fire of conscious will illuminates your inner world. Active spiritual practices — breathwork, dynamic meditation, or confronting subconscious fears — bring more results than passive contemplation.',
    },
  },
  taurus: {
    general: 'The Sun in Taurus slows the pace and grounds the collective energy in what is tangible and enduring. This is a season for building, savouring, and tending to what matters most. Values come into focus — financial, personal, and relational. Steady effort yields lasting results now.',
    themeKeywords: ['stability', 'sensuality', 'values', 'persistence'],
    personalByHouse: {
      1: 'The Taurus Sun steadies your identity and grounds you in your body. This season asks you to slow down, appreciate the beauty of your life as it is, and build on what feels genuinely solid.',
      2: 'Financial matters take centre stage with practical determination. This is your season to build material security, invest wisely, and develop a deeper relationship with your own values and self-worth.',
      3: 'Your communication style becomes more deliberate and substantial. People value your words because they carry weight and sincerity. This is a good time for important conversations that require patience and honesty.',
      4: 'Creating a beautiful, comfortable home environment becomes a priority. Invest in quality over quantity — a well-made piece of furniture, a thriving garden, or a kitchen that nourishes body and soul.',
      5: 'Sensual, tactile creative expression flourishes. Work with materials you can touch — clay, fabric, wood, food. Romantic connections deepen through shared physical experiences and unhurried pleasure.',
      6: 'Sustainable health practices take root during this season. Focus on nourishment rather than restriction, pleasure rather than punishment. Your body thrives on consistency, quality food, and adequate rest.',
      7: 'Stability and loyalty become the foundation of your partnerships. This is a time for building lasting commitment rather than chasing excitement. Show your love through consistent, reliable presence.',
      8: 'Deep change moves at a slower, more grounded pace. Rather than sudden upheaval, transformation comes through steady, patient work with your deeper patterns. Trust the process without rushing.',
      9: 'Your search for meaning favours direct experience over abstract theory. Travel to beautiful places, study traditions rooted in nature and the body, or explore philosophies that honour the material world.',
      10: 'Professional success comes through steady, quality work rather than flashy moves. Build your reputation on reliability and excellence. The efforts you make now compound into lasting achievement.',
      11: 'You contribute most to your communities through practical, tangible support. Rather than grand plans, offer your time, skills, and resources to create something real and lasting for the groups you value.',
      12: 'Earth-based spirituality nourishes your inner life. Spending time in nature, practising body-awareness meditation, or engaging with the sacred through sensory experience brings genuine transcendence.',
    },
  },
  gemini: {
    general: 'The Sun in Gemini fills the atmosphere with curiosity, conversation, and mental agility. Ideas circulate rapidly, social connections multiply, and there is a collective hunger for variety and stimulation. This is a season for learning, writing, and exploring multiple perspectives without needing to settle on one.',
    themeKeywords: ['curiosity', 'communication', 'versatility', 'learning'],
    personalByHouse: {
      1: 'The Gemini Sun multiplies your interests and social energy. Your identity feels versatile and curious — embrace the many facets of who you are without needing to choose just one.',
      2: 'Multiple income streams or creative financial thinking are favoured. Your ability to see opportunities others miss can translate into practical value. Diversify your approach to earning and spending.',
      3: 'This is your season for words, ideas, and connection. Writing, speaking, teaching, and all forms of communication are powerfully activated. Your message reaches further than usual — use this influence wisely.',
      4: 'Your home becomes a hub of activity and conversation. Family communications, neighbourhood connections, and creating a stimulating domestic environment keep you engaged and emotionally satisfied.',
      5: 'Playful intellectual creativity abounds. Writing, wordplay, collaborative projects, and art that tells a story thrive. Romance benefits from wit, conversation, and the willingness to keep things light and interesting.',
      6: 'Variety in your daily routines prevents boredom and keeps you healthy. Change your workout, try new foods, or rearrange your work schedule. Mental stimulation is as important as physical activity for your wellbeing.',
      7: 'Communication is the lifeblood of your partnerships this season. Talk more, listen more, and stay curious about your partner\'s inner world. The best relationships are ongoing conversations.',
      8: 'Deep change comes through understanding and articulation. Name what you feel, write about your shadows, and talk through your transformation with a trusted person. Words have healing power now.',
      9: 'Your mind is insatiable — every subject leads to three more. Allow yourself to follow intellectual threads without guilt. Cross-pollination between different fields of knowledge produces your most original insights.',
      10: 'Versatility and communication skills advance your professional standing. Present, network, write, and share your ideas. Being known as someone who connects dots and communicates clearly is a powerful career asset.',
      11: 'Social connections proliferate and energise your sense of purpose. You are the network builder — introduce people to each other, share information generously, and let your social intelligence serve the collective.',
      12: 'Your inner world buzzes with thoughts and questions. Rather than seeking silence, engage with spiritual teachings through reading, discussion, or contemplative writing. Let your mind be a vehicle for transcendence.',
    },
  },
  cancer: {
    general: 'The Sun in Cancer turns the collective attention inward — toward home, family, and emotional roots. Sensitivity is heightened, and there is a deep need for belonging and safety. This is a season for nurturing, for tending to inner wounds, and for creating spaces that feel like sanctuary.',
    themeKeywords: ['nurturing', 'home', 'emotional depth', 'belonging'],
    personalByHouse: {
      1: 'The Cancer Sun softens your outer shell and connects you more deeply with your emotional core. This season asks you to lead with sensitivity, trust your instincts, and honour your need for safety.',
      2: 'Financial security takes on emotional significance. Building a nest egg, investing in your home, or ensuring your family\'s material wellbeing feels like an act of love rather than mere practicality.',
      3: 'Your words carry emotional depth and nurturing warmth. Conversations with siblings, neighbours, and close contacts become more intimate. Express your care through thoughtful messages and heartfelt speech.',
      4: 'Your home and family life is powerfully illuminated this season. This is the time to deepen family bonds, improve your living space, and create an environment that feels truly safe and nourishing.',
      5: 'Creative expression drawn from your emotional life and personal memories is deeply moving. Art, cooking, storytelling, or any creative act that comes from the heart resonates powerfully. Romance feels tender and protective.',
      6: 'Your physical health is closely tied to your emotional state right now. Comfort eating, stress, or unprocessed feelings can manifest in your body. Nurture yourself holistically — body, mind, and heart together.',
      7: 'You bring nurturing energy to your partnerships and seek the same in return. Emotional safety and trust are the foundations you need. Create space for vulnerability — it deepens intimacy profoundly.',
      8: 'Deep emotional healing is available this season. Old wounds related to family, attachment, and belonging surface for resolution. Allow yourself to grieve what needs grieving and release what needs releasing.',
      9: 'Your quest for meaning draws from ancestral wisdom, family traditions, and emotional truth. Travel to places with personal or family significance brings unexpected insight and a deeper sense of belonging.',
      10: 'Emotional intelligence becomes your greatest professional asset. Lead with empathy, build a supportive team culture, and trust your instincts about people and situations. Authentic care earns lasting respect.',
      11: 'You seek to nurture and be nurtured within your social circles. Creating a sense of family among friends, hosting gatherings, and caring for your community members feels deeply purposeful.',
      12: 'Your spiritual life becomes deeply emotional and instinctive. Dreams, ancestral connections, and intuitive practices are heightened. Retreat into solitude when you need to — your inner world is rich and alive.',
    },
  },
  leo: {
    general: 'The Sun in Leo radiates warmth, creativity, and a desire to be fully expressed. This is the height of summer energy — bold, generous, and unapologetically alive. The collective mood favours celebration, artistic expression, and heartfelt leadership. Let your light shine without apology.',
    themeKeywords: ['creativity', 'confidence', 'joy', 'self-expression'],
    personalByHouse: {
      1: 'The Leo Sun illuminates your identity with warmth, confidence, and creative power. This is your season to shine — step into the spotlight, express your authentic self, and inspire others through your example.',
      2: 'Generous impulses meet your financial life. Invest in quality, treat yourself and others, but ensure your spending reflects genuine values rather than ego. Your sense of self-worth directly affects your earning potential now.',
      3: 'Your words carry dramatic flair and heartfelt passion. Presentations, creative writing, and public speaking are powerfully favoured. Speak from the heart — authenticity is more compelling than perfection.',
      4: 'Bringing warmth, celebration, and creative energy into your home life is the focus. Host, decorate, create family traditions, or simply fill your living space with more light and joy.',
      5: 'This is one of the most creatively potent seasons for you. Artistic expression, romance, playful joy, and anything that allows your heart to sing are deeply favoured. Do not hold back.',
      6: 'Approach your daily health routines with pride and pleasure rather than obligation. Exercise that feels celebratory, food that delights, and work that lets you take pride in your craft all support your wellbeing.',
      7: 'Your partnerships thrive when you bring your full, radiant self. Share your light generously with your closest person, and welcome their light equally. The best relationships celebrate both people fully.',
      8: 'Deep change asks you to let go of ego attachments. What you cling to out of pride may be exactly what needs to be released. The most courageous act is allowing yourself to be vulnerable.',
      9: 'Your spirit reaches for grand experiences and inspiring knowledge. Travel to places that awe you, study subjects that set your imagination ablaze, or share your wisdom through teaching and storytelling.',
      10: 'Professional authority and creative leadership are your superpowers this season. Step into visible roles, present your vision boldly, and trust that your natural warmth draws the right opportunities toward you.',
      11: 'Your generous spirit inspires and energises your social circles. Lead by example, celebrate others\' achievements as warmly as your own, and use your charisma to rally people around meaningful causes.',
      12: 'Creative visualisation, heart-centred prayer, and devotional practice suit your spiritual temperament right now. Your inner world needs warmth and purpose — approach the sacred with the same passion you bring to life.',
    },
  },
  virgo: {
    general: 'The Sun in Virgo shifts the focus toward refinement, service, and practical improvement. The expansive energy of Leo gives way to a quieter dedication to craft, health, and the details that hold life together. This is a season for getting organised, healing old patterns, and honouring the sacred in the ordinary.',
    themeKeywords: ['service', 'health', 'refinement', 'practical wisdom'],
    personalByHouse: {
      1: 'The Virgo Sun refines your sense of self with analytical clarity and a desire for genuine improvement. This season asks you to serve, heal, and attend to the details of becoming your best self.',
      2: 'Financial precision and practical budgeting come naturally. This is an excellent time for sorting through accounts, eliminating waste, and building a more efficient relationship with money and resources.',
      3: 'Your thinking and communication are sharp, precise, and detail-oriented. Editing, analysis, and carefully crafted messages are strongly favoured. Your clarity of expression earns trust and respect.',
      4: 'Domestic organisation and improvement take priority. Decluttering, repairing what is broken, and creating a more functional home environment brings deep satisfaction and emotional stability.',
      5: 'Craftsmanship and technical skill elevate your creative work. This is a season for refining your art rather than starting from scratch — polish, edit, and perfect. The details matter, and they show.',
      6: 'Your health and daily routines are powerfully in focus. Establish sustainable habits, address nagging health concerns, and approach your wellbeing with the same care and precision you bring to your best work.',
      7: 'Practical devotion defines your partnerships. Show love through acts of service, problem-solving together, and attending to the small things that make daily life run smoothly. Helpfulness is your love language now.',
      8: 'Analytical self-examination yields genuine breakthroughs. Systematically exploring your patterns, triggers, and deeper motivations — perhaps through therapy or structured journaling — leads to meaningful healing.',
      9: 'Applied learning and practical skill development appeal more than abstract philosophy. Workshops, certifications, or study programmes that give you usable knowledge satisfy your hunger for growth.',
      10: 'Professional excellence through meticulous work and genuine service advances your reputation. This is not a season for self-promotion but for letting the quality of your work speak for itself.',
      11: 'Your communities benefit most from your practical contributions. Organising events, solving logistical problems, or offering skilled help is how you make your most meaningful social impact.',
      12: 'Mindfulness and body-based practices ground your spiritual life in daily reality. Meditation focused on present-moment awareness, service to others, and finding the sacred in ordinary tasks brings genuine transcendence.',
    },
  },
  libra: {
    general: 'The Sun in Libra brings balance, beauty, and relationship into the collective spotlight. The equinox energy asks everyone to find equilibrium — between self and other, giving and receiving, action and rest. This is a season for diplomacy, aesthetic appreciation, and meaningful partnership.',
    themeKeywords: ['balance', 'partnership', 'beauty', 'diplomacy'],
    personalByHouse: {
      1: 'The Libra Sun brings grace, diplomacy, and aesthetic sensibility to your identity. This season asks you to find balance — between self and other, action and reflection, giving and receiving.',
      2: 'Financial decisions benefit from careful weighing of options and a focus on fairness. Joint financial arrangements, investments in beauty and culture, and balancing your budget with care are all favoured.',
      3: 'Diplomatic, graceful communication is your strength. Mediating disagreements, writing with elegance, and facilitating harmonious conversations comes naturally. Your words create bridges between people.',
      4: 'Creating aesthetic harmony in your home environment nourishes your soul. Beautiful interiors, balanced relationships with family members, and a peaceful domestic atmosphere are worth investing in.',
      5: 'Artistic expression infused with beauty, balance, and relational themes flourishes. Collaborative creative projects, romantic connection, and any art form that celebrates harmony resonates deeply with this season.',
      6: 'Balance is the guiding principle for your wellbeing. Neither extreme dieting nor indulgence — find the middle path. Graceful movement practices like dance or tai chi suit this Sun\'s energy perfectly.',
      7: 'Partnerships and one-on-one connections are powerfully illuminated this season. This is the time to deepen commitment, resolve imbalances, and co-create relationships that genuinely honour both people equally.',
      8: 'Deep transformation comes through relationship — the mirror of another person reveals what you cannot see alone. Couples therapy, honest dialogue with a trusted friend, or relational healing work is profoundly effective.',
      9: 'Cultural exploration, art history, philosophy of justice, and cross-cultural understanding captivate your mind. Travel to beautiful places or immerse yourself in a different aesthetic tradition to broaden your perspective.',
      10: 'Networking, diplomacy, and collaborative leadership advance your professional goals. Building alliances, mediating workplace tensions, and presenting ideas with charm and grace are your greatest career assets now.',
      11: 'Social harmony and collaborative vision define your community involvement. Bridge-building between different groups, creating beautiful shared spaces, and advocating for fairness within your social circles feels deeply purposeful.',
      12: 'Inner balance and peace are the goals of your spiritual practice. Meditation focused on equilibrium, contemplation of beauty as a doorway to the divine, and practices that harmonise your inner world bring deep serenity.',
    },
  },
  scorpio: {
    general: 'The Sun in Scorpio draws the collective gaze below the surface. This is a season of depth, intensity, and unflinching honesty. Hidden truths emerge, emotional power deepens, and transformation becomes possible for those willing to look into the shadows. Trust the process of dying and being reborn.',
    themeKeywords: ['transformation', 'intensity', 'truth', 'power'],
    personalByHouse: {
      1: 'The Scorpio Sun empowers your identity with intensity, depth, and transformative potential. This season asks you to be fearlessly authentic — to embrace your power and your vulnerability in equal measure.',
      2: 'Financial matters take on strategic intensity. This is a powerful time for eliminating debt, investigating investments, or transforming your relationship with money and resources at a fundamental level.',
      3: 'Your words penetrate beneath the surface. Conversations become more honest, probing, and potentially uncomfortable — but also more genuinely healing. Speak truth carefully, and listen for what others are really saying.',
      4: 'Deep emotional currents flow through your home and family life. Secrets may surface, old dynamics may shift, and the opportunity for genuine healing within your closest bonds is profound.',
      5: 'Creative expression drawn from your deepest emotions — grief, desire, rage, ecstasy — produces work of genuine power. Do not flinch from intensity in your art or your romantic life.',
      6: 'Detoxification, elimination, and confronting hidden health issues are strongly favoured. Address what you have been avoiding. Your body\'s capacity for regeneration is remarkable when you give it what it truly needs.',
      7: 'Partnerships require radical honesty and emotional courage this season. Surface-level connection no longer satisfies — you need intimacy that goes to the bone. This can be uncomfortable but profoundly bonding.',
      8: 'This is your most powerful season for deep inner work. Psychological healing, shadow integration, and allowing complete emotional rebirth are all available. Trust the process, even when it feels like destruction.',
      9: 'Your quest for truth cuts through comfortable illusions. Esoteric knowledge, depth psychology, investigative research, or travel to places with intense spiritual energy calls you toward deeper understanding.',
      10: 'Strategic professional power is available to you. Navigate workplace politics with insight, make career moves with precision, and allow your authentic intensity to command respect rather than hiding it.',
      11: 'You seek depth and authenticity in your social connections. Groups focused on healing, transformation, or social justice resonate. Your willingness to go deep inspires others to do the same.',
      12: 'The unseen world feels closer than ever. Meditation, dream work, ancestral healing, and practices that explore the threshold between life and death bring genuine spiritual power and transformation.',
    },
  },
  sagittarius: {
    general: 'The Sun in Sagittarius expands the horizon and fills the air with optimism, adventure, and philosophical inquiry. This is a season for travel — of body or mind — and for asking the big questions about meaning, purpose, and belief. Generosity and faith in the future come naturally now.',
    themeKeywords: ['adventure', 'wisdom', 'expansion', 'optimism'],
    personalByHouse: {
      1: 'The Sagittarius Sun fills your identity with optimism, wanderlust, and philosophical fire. This season asks you to expand your horizons, trust your vision, and share your enthusiasm with the world.',
      2: 'Generous financial impulses and big-picture thinking characterise your approach to money. Invest in experiences, education, or ventures with long-term growth potential rather than accumulating for security alone.',
      3: 'Your words carry inspiring, visionary energy. Teaching, publishing, public speaking, and conversations that explore the meaning of life are all strongly favoured. Speak your truth with confidence.',
      4: 'You may feel restless at home, craving more space or freedom within your domestic life. Bring the spirit of adventure indoors — international decor, philosophical family discussions, or hosting visitors from afar.',
      5: 'Expansive, ambitious creative projects call to you. Think bigger than usual — write the book, stage the performance, or pursue the artistic vision that has been quietly growing. Romance feels adventurous and free.',
      6: 'Active, outdoor-oriented health practices suit this season perfectly. Hiking, sports, or any movement that feels like adventure rather than obligation keeps your body and spirit thriving.',
      7: 'Freedom and growth are the gifts you bring to partnerships. Encourage your closest person to expand alongside you, and welcome the ways they challenge your assumptions. The best relationships help both people grow.',
      8: 'Deep change becomes meaningful when you can see the purpose in it. Finding wisdom in your pain, extracting the lesson from the crisis, and trusting that every ending is a beginning keeps you moving forward.',
      9: 'This is your most potent season for expansion of every kind. Travel, higher education, spiritual pilgrimage, or simply following your curiosity into unfamiliar territory yields extraordinary growth and insight.',
      10: 'Visionary leadership and big-picture thinking advance your professional standing. Position yourself as someone with a clear philosophy and a long-term vision. Your optimism and ambition inspire confidence.',
      11: 'You are the visionary within your social circles. Rally your community around an inspiring cause, share your knowledge generously, and build networks that connect people across cultural and ideological boundaries.',
      12: 'Your inner life expands toward the universal and the transcendent. Meditation, prayer, or contemplation that connects you to something greater than your individual story brings profound peace and renewed purpose.',
    },
  },
  capricorn: {
    general: 'The Sun in Capricorn coincides with the winter solstice and the return of the light, yet the energy is focused and serious. This is a season for setting long-term goals, taking responsibility, and building structures that will endure. Discipline and ambition are the gifts of this cardinal earth transit.',
    themeKeywords: ['ambition', 'discipline', 'structure', 'endurance'],
    personalByHouse: {
      1: 'The Capricorn Sun endows your identity with quiet authority, discipline, and determination. This season asks you to take responsibility for your life, set meaningful goals, and build structures that endure.',
      2: 'Long-term financial planning and disciplined saving are powerfully favoured. Build wealth slowly and wisely — the foundation you lay now will support you for years. Material security is a worthy goal.',
      3: 'Your words carry weight and authority. Business communication, strategic planning conversations, and practical advice are received with respect. Speak from experience and people will listen.',
      4: 'Strengthening the foundations of your domestic life — literally and emotionally — is the focus. Home repairs, establishing family traditions, or creating more structure in your household brings lasting satisfaction.',
      5: 'Disciplined creative practice yields your best work this season. Set yourself a challenge, work within structure, and commit to mastering your craft. The joy comes from achieving something you can be proud of.',
      6: 'Building sustainable, long-term health habits is the priority. Focus on consistency over intensity — the daily walk matters more than the occasional sprint. Your body rewards commitment with lasting vitality.',
      7: 'Mature, committed partnerships are the focus. This season favours building lasting relationship structures — shared goals, clear agreements, and mutual respect as the foundation of enduring love.',
      8: 'Deep change requires patience and steady effort rather than dramatic upheaval. Work through your shadows methodically, with the same discipline you bring to your professional life. Lasting transformation takes time.',
      9: 'Traditional wisdom, established teachers, and time-tested knowledge appeal more than experimental approaches. Structure your learning — formal education, apprenticeship, or systematic study — for the most lasting growth.',
      10: 'This is your most powerful season for professional achievement. Set ambitious goals, step into authority, and let your competence and dedication speak for themselves. Career milestones are within reach.',
      11: 'Your contribution to community and social causes is most effective when it is practical and organised. Build infrastructure, create systems, and lead with quiet competence. Lasting change requires lasting structures.',
      12: 'Disciplined spiritual practice — regular meditation, structured retreat, or systematic study of a tradition — brings deeper results than sporadic exploration. Commit to a path and walk it with patience.',
    },
  },
  aquarius: {
    general: 'The Sun in Aquarius electrifies the collective with innovation, humanitarian ideals, and a desire for freedom. Convention is questioned, individuality is celebrated, and community becomes more important than personal glory. This is a season for visionary thinking and progressive action.',
    themeKeywords: ['innovation', 'community', 'freedom', 'vision'],
    personalByHouse: {
      1: 'The Aquarius Sun electrifies your identity with originality, independence, and humanitarian vision. This season asks you to be authentically yourself — even when that means standing apart from the crowd.',
      2: 'Innovative financial thinking and unconventional approaches to earning and spending are favoured. Consider ethical investments, community-based economics, or creative revenue streams that align with your progressive values.',
      3: 'Original, progressive ideas flow through your conversations and writing. Your unique perspective on shared concerns resonates widely. Challenge conventional thinking and share your vision for a better future.',
      4: 'Your domestic life may benefit from technological upgrades, unconventional living arrangements, or simply breaking free from inherited patterns about what home and family should look like.',
      5: 'Experimental, innovative, and technologically informed creative expression thrives. Push boundaries, collaborate across disciplines, and create art that challenges convention. The future of creativity flows through you.',
      6: 'Progressive and science-informed approaches to health and wellness appeal strongly. Question inherited health assumptions, explore cutting-edge research, and design routines that are as unique as you are.',
      7: 'Freedom and intellectual connection are what you need most in partnerships. The most fulfilling relationships this season are those that respect individuality while sharing a commitment to mutual growth and a better world.',
      8: 'Detaching from outdated psychological patterns becomes possible through intellectual clarity and the willingness to see yourself objectively. Sometimes the deepest change comes from simply deciding to think differently.',
      9: 'Futuristic thinking, scientific discovery, and progressive philosophy captivate your mind. Explore ideas that are ahead of their time — your capacity to see beyond the present moment is a genuine gift.',
      10: 'Innovation and visionary thinking set you apart professionally. Position yourself at the forefront of change in your field, propose unconventional solutions, and build a reputation as someone who sees what is coming next.',
      11: 'This is your most powerful season for collective action and social vision. Organise, connect, and lead communities toward progressive change. Your ability to unite individuals around shared ideals is extraordinary.',
      12: 'A humanitarian spirituality that connects inner growth with collective evolution resonates deeply. Meditation that expands consciousness beyond the personal self, or service-oriented practice, brings your spiritual life alive.',
    },
  },
  pisces: {
    general: 'The Sun in Pisces dissolves boundaries between the seen and unseen. Intuition is heightened, creativity flows freely, and compassion comes naturally. This is a season for dreaming, healing, and connecting to something greater than yourself. The final sign prepares the soul for rebirth.',
    themeKeywords: ['intuition', 'compassion', 'creativity', 'surrender'],
    personalByHouse: {
      1: 'The Piscean Sun infuses your identity with heightened sensitivity and creative vision. Others may see you as more compassionate and intuitive than usual. Lean into this — your empathy is a strength.',
      2: 'Material concerns may feel less urgent as spiritual and emotional needs take priority. This is not the time for aggressive financial planning but for reflecting on what truly constitutes abundance in your life.',
      3: 'Your words carry poetic resonance and emotional depth. Creative writing, compassionate conversations, and communication that comes from the heart rather than the head moves people deeply.',
      4: 'Your home becomes a sanctuary and a temple. Creating a dreamy, nurturing atmosphere — with art, music, soft lighting, and sacred objects — nourishes your emotional and spiritual wellbeing profoundly.',
      5: 'Your creative expression deepens profoundly. Artistic projects, playful exploration, and romantic connections all carry a dreamlike, inspired quality. Follow what moves you emotionally — the muse is close.',
      6: 'Sensitivity to your environment is heightened this season. Prioritise gentle, holistic approaches to health — water-based therapies, energy healing, adequate sleep, and avoiding substances or environments that overwhelm your system.',
      7: 'Unconditional compassion and spiritual connection define your partnerships. You seek a soul-level bond rather than surface compatibility. Ensure that your empathy does not lead you to lose yourself in another person.',
      8: 'Surrender is the pathway to your deepest transformation. Rather than fighting change, allow yourself to dissolve into it. The Piscean gift is knowing that what falls apart often reconstitutes into something more beautiful.',
      9: 'Mystical traditions, spiritual pilgrimage, and transcendent experiences call you beyond the ordinary. Travel to sacred places, study ancient wisdom, or simply follow the thread of your deepest spiritual longing.',
      10: 'Creative, healing, and service-oriented professional paths are strongly illuminated. Your career thrives when it connects to something meaningful beyond personal advancement. Trust your intuition about professional direction.',
      11: 'Communities centred on healing, spirituality, art, or compassionate service resonate most deeply. Your empathic presence and creative gifts uplift any group you choose to be part of.',
      12: 'This is a potent time for your inner life. Meditation, journaling, and solitary reflection feel especially nourishing. You may have vivid dreams or unexpected spiritual insights. Trust what comes from the depths.',
    },
  },
}
